name = "Napalm beetle"
uid = "eb1d1f6c-1136-11eb-adc1-0242ac120002"
version = 1
description = "Turns fire beetles into napalm bombs"
author = "BlackYps"
selectable = true
enabled = true
exclusive = false
ui_only = false
